### ISSUE TITLE
Add input parameters so SnowRide can be started with concrete robots and a link to shared resources

### ISSUE THREAD

**Issue by voracfil** [Soothsilver/snowride#65]
RIDE allowed to specify path to shared resources and to robots directly during start up via command line parameters. Such a feature is necessary for us to use SnowRide efficiently.

**Comment by Soothsilver** [comment]
Spec:
Allow Snowride to load ".snow" files, either as command line arg ("java -jar snowride.jar configuration.snow") or by loading them from "Project->Open...").  You can create these files manually or export them from Snowride using "Project->Save project as...". When you make a change with a .snow file loaded, it's written through to the snow file when you next save.

A .snow file looks like this:
```
Directory=C:\robots
AdditionalPaths=C:\xmls;C:\pythonlibs
RunnerScript=C:\runner.bat
```
Paths can be relative to the working directory.

**Comment by Soothsilver** [comment]
So a `.snow` file is a Java properties file and looks like in the comment above.

It contains the path to shared resources and to the suite itself, and also to the runner script. You can load it either by putting it as the first command line argument or by loading it from the Project menu.

You can create the `.snow` file manually, but you'll probably want to create by using Project->Export.

I don't know how to easily share `.snow` files with source control. If you don't need that, then you can create a .snow file for each suite you work with and load them instead of the directories. You can set up file associations for .snow and Snowride if you know how (it's difficult on Windows 10) or you can create a launcher (maybe a .bat file). 

Except for the runner script, the paths can be relative to Snowride's working directory.
