### ISSUE TITLE
Renaming the keyword name should rename it in all places and tests that the keyword has been used

### ISSUE THREAD

**Issue by raghu19991** [Soothsilver/snowride#79]
When a keyword is renamed we are having to go to all locations that it has been used and modify it there as well.Since this is manual work sometimes we miss out modifying at some places.

Ideally I would have expected that renaming the keyword will also change it in all places across the project where it is used. It works fine in RIDE.

**Comment by Soothsilver** [comment]
Yeah, that's missing now. I think Snowride will say something like "Renaming keywords not supported yet".

It works fine in RIDE but not great. What RIDE does, I think, is that it replaces all cells which link to that keyword with the new name, plus it's probably doing some magic around gherkin keywords and qualified names. 

But the problem even in RIDE is that when you pass a string that looks like a keyword to another keyword, the IDE doesn't know if it should be renamed or not. Suppose you have a keyword called "DoBusiness" and want to rename it, and you encounter the line "My Keyword | Do Business". Should the IDE replace "Do Business"? Is it used as a string, perhaps to put into a log, or as a keyword, to be executed by "Run Keyword" inside "My Keyword"?

RIDE always chooses to replace it, which is why I didn't feel safe using the "Rename" feature in RIDE. But if the IDE choose to _not_ replace everything, then it can miss some instances! Either way you would still want to check manually.

I suppose the best thing would be to do what RIDE is doing, but what do you think?

**Comment by Soothsilver** [comment]
Fixed in 2.7.
